authors:
  dipanwita:
    name: Dipanwita Guhathakurta
    description: " "
    avatar: https://github.com/susiejojo.png
  mert:
    name: Mert Toslali
    description: " "
    avatar: https://github.com/toslali-ibm.png
  jing:
    name: Jing Chen
    description: " "
    avatar: https://github.com/jgchn.png
  nick:
    name: Nick Masluk
    description: " "
    avatar: https://github.com/namasl.png
  michael:
    name: Michael Kalantar
    description: " "
    avatar: https://github.com/kalantar.png
  asser:
    name: Asser Tantawi
    description: " "
    avatar: https://github.com/atantawi.png
  vishakha:
    name: Vishakha Ramani
    description: " "
    avatar: https://github.com/vishakha-r.png
  srini:
    name: Srinivasan Parthasarathy
    description: " "
    avatar: https://github.com/sriumcp.png
  fabio:
    name: Fabio Oliveira
    description: " "
    avatar: https://github.com/fabolive.png
